export const columns = {
    expDownload: [
        { header: "SL No", key: "serial_no"},
        { header: "AD Code", key: "ad_code" },
        { header: "Exp Serial", key: "exp_serial" },
        { header: "Exp Year", key: "exp_year" },
        { header: "Invoice No", key: "invoice_no" },
        { header: "Status", key: "status" },
        { header: "Edit", key: "edit" },
        { header: "Download", key: "download" },
        { header: "View Logs", key: "view_logs" }
    ],
    expIssuance: [
        { header: "SL No", key: "serial_no"},
        { header: "LC NO", key: "lc_no" },
        { header: "Commodity", key: "commodity" },
        {header: "Incoterm", key: "incoterm"},
        { header: "Country", key: "country" },
        {header:"Unit", key: "unit"},
        {header:"Quantity", key: "quantity"},
        {header:"Invoice No", key: "invoice_no"},
        {header:"Invoice Date", key: "invoice_date"},
        {header:"Invoice Amount", key: "invoice_amount"},
        {header:"Transportation Doc Type", key: "trans_doc"},
        {header:"Port of Shipment", key: "port"},
        {header:"Signatory", key: "signatory"},
        { header: "Status", key: "status" },
        { header: "Edit", key: "edit" },
        { header: "View Logs", key: "view_logs" }
    ],
    booking: [
        { header: "SL No", key: "serial_no"},
        { header: "Po No", key: "po_no" },
        { header: "Order No", key: "order_no" },
        { header: "Item", key: "item" },
        { header: "Gender", key: "gender" },
        { header: "Country Iso", key: "country_iso" },
        { header: "Delivery Time", key: "delivery_time" },
        { header: "Summary Marks", key: "summary_marks" },
        { header: "Summary Description", key: "summary_desc" },
        { header: "Pcs Per Pack", key: "no_of_pcs_per_pack" },
        { header: "Status", key: "status" },
        { header: "Edit", key: "edit" },
        { header: "View Logs", key: "view_logs" }

    ],
    fcr:[
        { header: "SL No", key: "serial_no"},
        { header: "Invoice No", key: "invoice_no" },
        { header: "Invoice Date", key: "invoice_date" },
        { header: "Exporter Ref", key: "exporters_ref" },
        { header: "HS Code", key: "hs_code" },
        { header: "Description", key: "description" },
        { header: "Composition", key: "composition" },
        { header: "Quantity", key: "quantity" },
        { header: "PO No", key: "po_no" },
        { header: "Country ISO", key: "country_iso" },
        { header: "Status", key: "fcr_status" },
        { header: "Edit", key: "edit" },
        { header: "View Logs", key: "view_logs" }
    ],
    commonLogs: [
        { header: "SL-NO", key: "serial_no"},
        { header: "Activity Type", key: "activity_type" },
        { header: "Activity", key: "activity" },
        { header: "Activity Time", key: "activity_time" },
        { header: "Draft", key: "draft" },
    ],
};
